name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.425

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android packages
      run: |
        sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

    - name: Install MAUI
      run: |
        dotnet workload install maui-android

    - name: Build APK
      run: |
        cd Instageram.Android
        dotnet restore
        dotnet publish -c Release -f net8.0-android -p:AndroidPackageFormat=apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Instageram-APK
        path: Instageram.Android/bin/Release/**/*.apk
