name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |`n          8.0.425

    - name: Install Android workload
      run: dotnet workload install maui-android

    - name: Build APK
      run: |
        cd Instageram.Android
        dotnet restore
        dotnet publish -f net8.0-android -c Release -p:AndroidPackageFormat=apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Instageram-APK
        path: Instageram.Android/bin/Release/**/*.apk
