name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI
      run: dotnet workload install maui-android

    - name: Build APK
      run: |
        cd Instageram.Android
        dotnet publish -f net8.0-android -c Release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Instageram-APK
        path: Instageram.Android/bin/Release/**/*.apk
